version: "3.8"
services:
  db:
    image: postgres
    ports:
      - "6000:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pensieve_dev
    volumes:
      - db-storage:/var/lib/postgresql/data
    restart: always

  api:
    build: api
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db/pensieve_dev
      - APP_SETTINGS=config.DevelopmentConfig
    command: /app/entrypoint.sh
volumes:
  db-storage:
